### ISSUE TITLE
Update B2B image

### ISSUE THREAD

**Issue by G2CARBZ** [Carbonable/carbonable-home#50]
**Description**
---
The current website on prod still has the old school screenshot
And the one on dev doesn't use the last version

Please adjust with the one attached here and push it on prod when possible. 

![Group 6561-min](https://user-images.githubusercontent.com/100774645/204791797-5ca13935-63e3-4a94-a4ca-ccdda3f7febf.png)

**Comment by schwepps** [comment]
@cloudvenger tu pourrais mep la home? On a oublié de le faire quand on a update l'image.

**Comment by cloudvenger** [comment]
The home page with the right img is in production:
https://carbonable.io/
