### ISSUE TITLE
[Update] Put back into service Carbonable Simulator

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-home#64]
**Description**
---
Put back into service Carbonable Simulator

**Acceptance Criteria**
---

- [ ] A dedicated page for Simulator Yield
- [ ] A specific Domain Name for this page

**Comment by schwepps** [comment]
To be done alongside https://app.zenhub.com/workspaces/product-tech-team-workspace-64527a8c74b9f900123e10f6/issues/gh/carbonable/carbonable-dapp/110

**Comment by schwepps** [comment]
Estimated 2 points but took a bit longer (3) to adapt new design
